server:
  port: 9537
spring:
  application:
    name: msa-weather-collection-eureka-feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true